---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - firefox
      - wezterm
      - maccy
      - orbstack
      - tomatobar
    brew_packages:
      - bash-completion
      - stow
      - git
      - tmux
      - neovim
      - coreutils
      - mpv
      - streamlink
      - lazygit
      - nvm
      - make
      - gcc
      - ripgrep
      - unzip
      - fzf
      - fd
      - newsboat
      - pandoc
      - glow
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Apply macOS tasks
      when: ansible_os_family == "Darwin"
      block:
        - name: Set HomeBrew path
          ansible.builtin.set_fact:
            homebrew_path: /usr/local/bin/brew
          when: ansible_architecture != "arm64"

        - name: Set HomeBrew path
          ansible.builtin.set_fact:
            homebrew_path: /opt/homebrew/bin
          when: ansible_architecture == "arm64"

        - name: Ensuring Homebrew Is Installed
          ansible.builtin.stat:
            path: "{{ homebrew_path }}"
          register: homebrew_check

        - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
          ansible.builtin.fail:
            msg: Homebrew is missing...Install from http://brew.sh/
          when:
            - not homebrew_check.stat.exists
            - not install_homebrew_if_missing|bool

        - name: Installing Homebrew
          ansible.builtin.shell:
            cmd: yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          when:
            - not homebrew_check.stat.exists
            - install_homebrew_if_missing|bool

  tasks:
    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
