#!/usr/bin/env bash

# Install Command line tools
xcode-select --install

# Prepare python install
export PATH="$HOME/Library/Python/3.9/bin:/opt/homebrew/bin:$PATH"
sudo pip3 install --upgrade pip

# Install Ansible
pip3 install ansible

# Clone needed repositories for ansible playbook and dotfiles
git clone https://github.com/bnto/spunto $1
git clone --recursive https://github.com/bnto/dotfiles $1

# Set bash as default shell
# chsh -s /bin/bash
# /bin/bash

# Start installation
ansible-playbook spunto/install.yml

echo "Setup Finished"
