#!/usr/bin/env bash

# Install Command line tools
xcode-select --install

# Wait for user confirmation or for xcode-select to finish if it requires input
echo "Please complete the Xcode Command Line Tools installation and press Enter to continue..."
read -p ""

# Prepare python install
export PATH="$HOME/Library/Python/3.9/bin:/opt/homebrew/bin:$PATH"
sudo pip3 install --upgrade pip

# Install Ansible
pip3 install ansible

# Clone needed repositories for ansible playbook and dotfiles
git clone https://github.com/bnto/spunto $1
git clone --recursive https://github.com/bnto/dotfiles $1

# Start installation
ansible-playbook spunto/install.yml --verbose

# Set bash as default shell
chsh -s /bin/bash
/bin/bash

# Prepare homebrew
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

# Set dotfiles
stow -t ~ -d dotfiles bash

echo "Setup Finished"
